const fs = require('fs');
let c = fs.readFileSync('src/jsx/modals.jsx', 'utf8');

const target = `{err.startsWith("DECRYPTION_FAILED:") || err.startsWith("DEVICE_LOCKED:") ? (<div><p>{err.includes(':') ? err.split(':')[1] : err}</p><button type="button" onClick={async () => { if(confirm('This will PERMANENTLY ERASE your cloud vault and reset it for this device. Are you sure?')) { const emailHash = await AppDB.hashKey(e.trim().toLowerCase()); const vault = await AppDB.getFile(\`gl_vault_\${emailHash}.json\`); vault.content = { profiles: [], settings: {} }; await AppDB.saveFile(\`gl_vault_\${emailHash}.json\`, vault.content, vault.sha); alert('Vault wiped. Please sign in again.'); setErr(''); } }} className="mt-2 w-full py-1.5 bg-red-500 text-black font-bold rounded">Wipe & Reset Vault</button></div>) : err}`;

const replace = `{err.startsWith("DECRYPTION_FAILED:") || err.startsWith("DEVICE_LOCKED:") ? (<div><p className="mb-2">{err.includes(':') ? err.split(':')[1] : err}</p><button type="button" onClick={() => { const keys = prompt("Paste your exported Device Encryption Key String:"); if(keys) { const success = CryptoUtils.importKeys(keys); if(success) { alert("Keys imported successfully! You can now log in."); setErr(''); } else { alert("Invalid key string."); } } }} className="w-full py-2 bg-blue-500 text-white font-bold rounded mb-2">Import Device Keys</button><button type="button" onClick={async () => { if(confirm('This will PERMANENTLY ERASE your cloud vault and reset it for this device. Are you sure?')) { const emailHash = await AppDB.hashKey(e.trim().toLowerCase()); const vault = await AppDB.getFile(\`gl_vault_\${emailHash}.json\`); vault.content = { profiles: [], settings: {} }; await AppDB.saveFile(\`gl_vault_\${emailHash}.json\`, vault.content, vault.sha); alert('Vault wiped. Please sign in again.'); setErr(''); } }} className="w-full py-1.5 bg-red-900/50 text-red-300 border border-red-500/30 text-xs rounded">Wipe & Reset Vault</button></div>) : err}`;

c = c.split(target).join(replace);
fs.writeFileSync('src/jsx/modals.jsx', c);
